import { Badge } from "@/components/atoms/Badge";
import { Heading } from "@/components/atoms/Heading";
import { Text } from "@/components/atoms/Text";
import type { CertificatePublicTemplateProps } from "@/components/templates/CertificatePublicTemplate/types/certificate-public-template.types";

export function CertificatePublicTemplate({ certificate, token }: CertificatePublicTemplateProps) {
  const revoked = certificate.status === "revoked";
  return <main className="mx-auto flex min-h-screen max-w-3xl items-center px-6 py-16"><article className="w-full space-y-7 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm sm:p-12"><div className="space-y-3"><Badge variant={revoked ? "warning" : "success"}>{revoked ? "Certificado revocado" : "Certificado vigente"}</Badge><Heading level={1}>{certificate.title}</Heading><Text className="text-lg">Emitido a <strong>{certificate.participant_name}</strong></Text></div><dl className="grid gap-5 rounded-2xl bg-slate-50 p-6 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Código</dt><dd className="font-mono font-semibold">{certificate.certificate_code}</dd></div><div><dt className="text-sm text-slate-500">Condición</dt><dd>{certificate.condition ?? "Participó"}</dd></div>{certificate.date_text ? <div><dt className="text-sm text-slate-500">Fecha</dt><dd>{certificate.date_text}</dd></div> : null}{certificate.academic_hours !== null ? <div><dt className="text-sm text-slate-500">Horas académicas</dt><dd>{certificate.academic_hours}</dd></div> : null}</dl>{revoked ? <p className="rounded-xl bg-amber-50 p-4 text-amber-900">Este certificado fue revocado y ya no está disponible para descarga. {certificate.revocation_reason ? `Motivo: ${certificate.revocation_reason}` : ""}</p> : <a className="inline-flex min-h-12 items-center justify-center rounded-xl bg-slate-950 px-5 font-semibold text-white" href={`/certificados/${token}/descargar`}>Descargar certificado PDF</a>}<Text size="sm">El token permite consultar únicamente este certificado y no expone datos administrativos.</Text></article></main>;
}
