import Link from "next/link";

import { Badge } from "@/components/atoms/Badge";
import { Heading } from "@/components/atoms/Heading";
import { Text } from "@/components/atoms/Text";
import type { CertificatePublicTemplateProps } from "@/components/templates/CertificatePublicTemplate/types/certificate-public-template.types";
import { ROUTES } from "@/constants/routes";
import { CertificateRecommendations } from "@/features/certificates/components/CertificateRecommendations";

export function CertificatePublicTemplate({ accountHref, accountLabel, certificate, recommendations, token }: CertificatePublicTemplateProps) {
  const revoked = certificate.status === "revoked";
  return <div className="bg-cci-50"><section className="bg-cci-950 px-4 py-10 sm:px-6 sm:py-16"><article className="mx-auto w-full max-w-3xl space-y-6 rounded-2xl border border-white/10 bg-white p-5 shadow-2xl sm:space-y-7 sm:rounded-[2rem] sm:p-12"><div className="space-y-3"><Badge variant={revoked ? "warning" : "success"}>{revoked ? "Certificado revocado" : "Certificado vigente"}</Badge><Heading level={1}>{certificate.title}</Heading><Text className="text-lg">Emitido a <strong>{certificate.participant_name}</strong></Text></div><dl className="grid gap-5 rounded-2xl bg-cci-100 p-5 sm:grid-cols-2 sm:p-6"><div className="min-w-0"><dt className="text-sm text-slate-500">Código</dt><dd className="break-all font-mono font-semibold">{certificate.certificate_code}</dd></div><div><dt className="text-sm text-slate-500">Tipo</dt><dd>{certificate.certificate_type === "course" ? "Curso" : "Actividad"}</dd></div><div><dt className="text-sm text-slate-500">Condición</dt><dd>{certificate.condition ?? "Participó"}</dd></div>{certificate.date_text ? <div><dt className="text-sm text-slate-500">Fecha</dt><dd>{certificate.date_text}</dd></div> : null}{certificate.academic_hours !== null ? <div><dt className="text-sm text-slate-500">Horas académicas</dt><dd>{certificate.academic_hours}</dd></div> : null}</dl>{revoked ? <p className="rounded-xl bg-amber-50 p-4 text-amber-900">Este certificado fue revocado y ya no está disponible para descarga. {certificate.revocation_reason ? `Motivo: ${certificate.revocation_reason}` : ""}</p> : certificate.download_available ? <a className="inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-cci-950 px-5 text-center font-semibold text-white hover:bg-cci-800 sm:w-auto" href={`/certificados/${token}/descargar`}>Descargar certificado PDF</a> : <p className="rounded-xl bg-cci-50 p-4 text-slate-700">El archivo todavía está siendo preparado.</p>}<div className="flex flex-wrap gap-4 border-t border-cci-100 pt-5"><Link className="text-sm font-semibold text-cci-800 underline" href={ROUTES.certificates}>Consultar otro DNI</Link><Link className="text-sm font-semibold text-cci-800 underline" href={accountHref}>{accountLabel}</Link></div></article></section><div className="mx-auto w-full max-w-7xl px-5 py-14 sm:px-8 sm:py-20"><CertificateRecommendations recommendations={recommendations} /></div></div>;
}
